name: Build & Push DockerHub Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  docker:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/banquito-sw-sft:prod -f docker/Dockerfile .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/banquito-sw-sft:prod

      - name: Trigger Infra Deploy
        run: |
          curl -f -i -X POST \
            -H "Authorization: Bearer ${{ secrets.DEVOPS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/CamilaParedes23/banquito-infra/dispatches \
            -d '{
              "event_type": "deploy-switch-back",
              "client_payload": {
                "service": "banquito-sw-sft"
              }
            }'
