name: Build & Push Artifact Registry Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

env:
  GAR_LOCATION: us-central1
  GCP_PROJECT_ID: banquitog2-p3
  GAR_REPOSITORY: banquito
  IMAGE_NAME: banquito-sw-sftp

jobs:
  docker:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Docker Auth for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build -t ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:prod -f docker/Dockerfile .

      - name: Push image
        run: |
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:prod

      # - name: Trigger Infra Deploy
      #   run: |
      #     curl -f -i -X POST \
      #       -H "Authorization: Bearer ${{ secrets.DEVOPS_TOKEN }}" \
      #       -H "Accept: application/vnd.github+json" \
      #       https://api.github.com/repos/CamilaParedes23/banquito-infra/dispatches \
      #       -d '{
      #         "event_type": "deploy-switch-back",
      #         "client_payload": {
      #           "service": "banquito-sw-sftp"
      #         }
      #       }' ddddddd
